### PR TITLE
Add Helm chart to repository

### PR DESCRIPTION
**Pull request by nachomillangarcia**
I've added the great work made by @alexpg in` /helm`. (see [issue](https://github.com/braedon/prometheus-es-exporter/issues/32))

This [other PR](https://github.com/helm/charts/pull/11871) to add it to the stable helm repository has been dismissed, and I think this work should be available from this repo. 

The code is exactly the same from that PR, didn't change anything. I can maintain this helm chart if you wish.

### CODE REVIEW

**Comment by braedon** [comment]
Hi @nachomillangarcia, thanks for pulling this across, and thanks @alexppg for the original work.

I see the value in having a helm chart (and have used helm myself), but I'm not entirely sure what's the best way to maintain one (or where).

I'll have a ponder, and try and work out where to go from here.

Feel free to give me a poke if I take too long!

**Comment by alexppg** [comment]
I was waiting to have my own helm repository, and I do since a few weeks ago. If you want to, I can host it there and you may reference it in the documentation. It's [here](https://github.com/little-angry-clouds/charts).

**Comment by nachomillangarcia** [comment]
It's not necessary to have a helm repository. Many projects maintain the Helm code in the same repo, I think it's the easiest for small projects.

Helm has support to install charts from git.

**Comment by alexppg** [comment]
Hi
It doesn't install from a git repository without cloning it first, as far as I know. There's a [plugin](https://github.com/aslafy-z/helm-git) that does it, though.
Anyway, it can be merged without problem.

**Comment by braedon** [comment]
Hi @nachomillangarcia, I've finally got a chart (based on @alexppg's work) in a helm repo (see [this comment](https://github.com/braedon/prometheus-es-exporter/issues/32#issuecomment-653488191) for details), so I'll close this PR. Thanks for submitting this though, and sorry it took so long to get sorted!

**Pull request closed without merging**
