### PR TITLE
Add a metric for the count of mapped fields by index and field type

### LINKED ISSUE #66: Total field metric
Do you have an example to create a prometheus metric out of the count of total fields? 

For example, under `management/kibana/index_patterns` you can see the total number of fields. I would like to create a prometheus metric so I can alert if there are 1000 fields or more.

### PR DESCRIPTION
**Pull request by braedon**
The new collector parses the `/_mappings` endpoint, producing the new `es_indices_mappings_field_count` metric. The labels `index` and `field_type` are available.

Closes #66

### CODE REVIEW

**Comment by braedon** [comment]
@jonny-wg2 Here's a quick attempt at getting the field count metric. Please take a look and let me know if it solves your use case.

The clusters I have to test on don't have very complex mappings, so it'd be great if you could run it against your cluster to make sure there aren't any mappings parsing issues. Let me know if you need an alpha version pushed to Dockerhub or PyPi to do this.

**Comment by jonny-wg2** [comment]
@braedon Awesome stuff!!

I just deployed this in my cluster and it works like a charm. In our usecase, we have two different indexes, logstash-xxx-date and logstash-yyy-date and It was able to pick these up. Also it separated the field mapping nice between keywords, objects, long, ips etc.

But again, awesome stuff! I wasn't able to find an exporter that has this metric, and I think it's one of the most important as an ES cluster will tend to fall over if there are more than 1000 fields in an index.

**Comment by braedon** [comment]
Sweet, I'll merge and cut a release.

**Comment by braedon** [comment]
Released in version [0.10.0](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.10.0)

**Pull request merged**
