### PR TITLE
Enable querying on ChaosSearch for generating prometheus metrics

### PR DESCRIPTION
**Pull request by jonny-wg2**
Fixes https://github.com/braedon/prometheus-es-exporter/issues/77

### CODE REVIEW

**Comment by braedon** [comment]
Hi @jonny-wg2, thanks for the PR. A couple of high level thoughts:

I don't know a lot (/anything) about ChaosSearch and Elasticsearch on AWS in general, but I wonder if there are other providers that could be supported with `requests_aws4auth`? Could we make the implementation generic (i.e. generify the click option names and documentation), and just have ChaosSearch as an example in the README? (I'd probably need to add a general auth section to the README, and include the ChaosSearch example under the AWS subsection.)

I also noticed quite a few unrelated whitespace changes in the diff. I use a 100 character line length for my projects, not 80, so I don't think these changes are necessary.

Let me know what you think.

**Comment by jonny-wg2** [comment]
Yeah I think those are all valid suggestions! I will update the pr with making it generic and fix the auto formatted spacing.

**Comment by braedon** [comment]
Hey @jonny-wg2, any update on this?

I can update the PR for you if you're short on time, but I'd still need your help with testing against AWS.

**Comment by jonny-wg2** [comment]
Hi, sorry - I have got caught up with a bunch of stuff. We are no longer
using chaos search, so I wouldn't be able to test using their cluster.

**Comment by braedon** [comment]
No worries. I'll close this for now then.

If someone else needs AWS auth support, I can take another look.

**Pull request closed without merging**
